[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["tokio-macros", "rt-multi-thread", "macros"] }
warp = { version = "0.4.2", features = ["server"] }
